-- Revision V3.8: Internationale Adressen für Impressums-/Personendaten

CREATE TABLE IF NOT EXISTS addresses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  to_person BIGINT UNSIGNED NOT NULL,
  address_type ENUM('business','residential','postal','billing','other') NOT NULL DEFAULT 'business',
  label VARCHAR(120) NOT NULL DEFAULT '',
  organization VARCHAR(190) NOT NULL DEFAULT '',
  department VARCHAR(190) NOT NULL DEFAULT '',
  care_of VARCHAR(190) NOT NULL DEFAULT '',
  address_line_1 VARCHAR(190) NOT NULL DEFAULT '',
  address_line_2 VARCHAR(190) NOT NULL DEFAULT '',
  address_line_3 VARCHAR(190) NOT NULL DEFAULT '',
  building VARCHAR(120) NOT NULL DEFAULT '',
  street_name VARCHAR(190) NOT NULL DEFAULT '',
  house_number VARCHAR(40) NOT NULL DEFAULT '',
  post_office_box VARCHAR(80) NOT NULL DEFAULT '',
  district VARCHAR(120) NOT NULL DEFAULT '',
  city VARCHAR(120) NOT NULL DEFAULT '',
  administrative_area VARCHAR(120) NOT NULL DEFAULT '',
  postal_code VARCHAR(40) NOT NULL DEFAULT '',
  country_code CHAR(2) NOT NULL DEFAULT 'DE',
  country_name VARCHAR(120) NOT NULL DEFAULT 'Deutschland',
  phone VARCHAR(80) NOT NULL DEFAULT '',
  email VARCHAR(190) NOT NULL DEFAULT '',
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  valid_from DATE NULL,
  valid_until DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_addresses_person (to_person),
  KEY idx_addresses_country_postal (country_code, postal_code),
  KEY idx_addresses_primary (to_person, is_primary),
  CONSTRAINT fk_addresses_person
    FOREIGN KEY (to_person) REFERENCES imprint_persons(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT chk_addresses_country_code CHECK (country_code REGEXP '^[A-Z]{2}$'),
  CONSTRAINT chk_addresses_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT chk_addresses_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  CONSTRAINT chk_addresses_validity CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
