CREATE TABLE IF NOT EXISTS add_index_content (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    internal_name VARCHAR(160) NOT NULL,
    title VARCHAR(255) NOT NULL DEFAULT '',
    position_no INT UNSIGNED NOT NULL DEFAULT 1,
    placement ENUM('before','after','replace') NOT NULL DEFAULT 'after',
    html_content MEDIUMTEXT NOT NULL,
    css_content MEDIUMTEXT NULL,
    js_content MEDIUMTEXT NULL,
    wrapper_class VARCHAR(255) NOT NULL DEFAULT '',
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 100,
    valid_from DATETIME NULL,
    valid_until DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_add_index_content_runtime (active, position_no, placement, sort_order),
    KEY idx_add_index_content_validity (valid_from, valid_until),
    CONSTRAINT chk_add_index_position CHECK (position_no BETWEEN 1 AND 1000),
    CONSTRAINT chk_add_index_active CHECK (active IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
