<?php
declare(strict_types=1);

return [
    'deutsch' => [
        'code' => 'DEU',
        'slug' => 'karriere-deutsch.php',
        'title' => 'Nachhilfelehrkraft Deutsch',
        'claim' => 'Sprache verständlich machen. Ausdruck stärken. Selbstvertrauen entwickeln.',
        'intro' => 'Gesucht werden Lehrkräfte, die Grammatik, Literatur, Rechtschreibung und schriftlichen Ausdruck nicht nur korrigieren, sondern nachvollziehbar vermitteln.',
        'subjects' => ['Deutsch', 'Deutsch als Zweitsprache', 'Literatur', 'Prüfungsvorbereitung'],
        'values' => ['Verstehen statt Auswendiglernen', 'Geduldige und klare Rückmeldung', 'Individuelle Stundenplanung', 'Respekt vor unterschiedlichen Ausdruckswegen'],
        'requirements' => ['Sehr sichere Deutschkenntnisse', 'Freude an Sprache, Texten und Literatur', 'Fähigkeit, Regeln anschaulich zu erklären', 'Zuverlässige Vor- und Nachbereitung'],
        'profiles' => ['Lehramts- oder Germanistikstudierende', 'Lehrkräfte und pensionierte Lehrkräfte', 'DaZ-/DaF-Fachkräfte', 'Fachlich geeignete Quereinsteigerinnen und Quereinsteiger'],
        'images' => [
            ['src' => '/assets/img/jobs/deutsch/deutsch-01-einzelunterricht.jpg', 'alt' => 'Lehrkraft begleitet eine Schülerin im individuellen Deutschunterricht', 'caption' => 'Persönlich erklären und gemeinsam verstehen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-05-grammatik-erklaeren.jpg', 'alt' => 'Lehrkraft erklärt Satzbau und Grammatik an einem Whiteboard', 'caption' => 'Grammatik sichtbar und verständlich machen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-04-schreibbegleitung.jpg', 'alt' => 'Lehrkraft unterstützt eine Schülerin beim Schreiben', 'caption' => 'Schreibprozesse aufmerksam begleiten'],
        ],
        'detail_images' => [
            ['src' => '/assets/img/jobs/deutsch/deutsch-08-empfang-easyit.jpg', 'alt' => 'Heller Empfangsbereich von easyIT Nachhilfe', 'caption' => 'Willkommen bei easyIT Nachhilfe'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-01-einzelunterricht.jpg', 'alt' => 'Lehrkraft begleitet eine Schülerin im individuellen Deutschunterricht', 'caption' => 'Individuelle Lernbegleitung'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-05-grammatik-erklaeren.jpg', 'alt' => 'Lehrkraft erklärt Satzbau und Grammatik an einem Whiteboard', 'caption' => 'Verstehen statt Auswendiglernen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-04-schreibbegleitung.jpg', 'alt' => 'Lehrkraft unterstützt eine Schülerin beim Schreiben', 'caption' => 'Schreiben Schritt für Schritt entwickeln'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-07-gruppenunterricht.jpg', 'alt' => 'Lehrkraft unterrichtet eine kleine Lerngruppe', 'caption' => 'Kleine Gruppen aufmerksam führen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-02-fachgespraech.jpg', 'alt' => 'Kolleginnen und Kollegen besprechen Unterrichtsmaterialien', 'caption' => 'Fachlicher Austausch im Team'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-03-kollegialer-austausch.jpg', 'alt' => 'Zwei Lehrkräfte tauschen sich mit Büchern aus', 'caption' => 'Materialien gemeinsam weiterentwickeln'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-06-unterrichtsplanung.jpg', 'alt' => 'Lehrkräfte planen Unterricht gemeinsam am Tisch', 'caption' => 'Unterricht sorgfältig vorbereiten'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-09-teammeeting.jpg', 'alt' => 'Teamgespräch in einem hellen Besprechungsraum', 'caption' => 'Offen und verbindlich zusammenarbeiten'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-10-fortbildung.jpg', 'alt' => 'Fortbildung mit Präsentation vor einer Gruppe', 'caption' => 'Fachlich und didaktisch weiterlernen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-11-kleingruppengespraech.jpg', 'alt' => 'Lehrkraft moderiert ein Gespräch in kleiner Runde', 'caption' => 'Gespräche auf Augenhöhe führen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-12-arbeitsrunde.jpg', 'alt' => 'Kollegiale Arbeitsrunde mit Unterlagen', 'caption' => 'Erfahrungen reflektieren'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-13-digitale-zusammenarbeit.jpg', 'alt' => 'Team arbeitet gemeinsam mit einem Notebook', 'caption' => 'Digitale Werkzeuge sinnvoll einsetzen'],
            ['src' => '/assets/img/jobs/deutsch/deutsch-14-methodenworkshop.jpg', 'alt' => 'Methodenworkshop mit Präsentation und Flipchart', 'caption' => 'Methoden gemeinsam prüfen und verbessern'],
        ],
        'faq' => [
            ['q' => 'Welche Deutschthemen werden besonders häufig nachgefragt?', 'a' => 'Häufig geht es um Rechtschreibung, Grammatik, Textverständnis, Aufsatzformen, Argumentation, Literaturarbeit und gezielte Prüfungsvorbereitung.'],
            ['q' => 'Muss ich Germanistik oder Lehramt studiert haben?', 'a' => 'Ein passendes Studium ist willkommen, aber nicht die einzige Möglichkeit. Entscheidend sind sehr sichere Deutschkenntnisse, fachliche Zuverlässigkeit und die Fähigkeit, verständlich zu erklären.'],
            ['q' => 'Wie individuell soll eine Stunde vorbereitet werden?', 'a' => 'Die Vorbereitung orientiert sich am konkreten Lernstand, am Schulstoff, an bisherigen Schwierigkeiten und am vereinbarten Lernziel. Vorgefertigte Materialien dürfen genutzt werden, ersetzen aber nicht die didaktische Auswahl.'],
            ['q' => 'Kann ich nur bestimmte Klassenstufen übernehmen?', 'a' => 'Ja. Die Zuordnung erfolgt nach fachlicher Sicherheit, Erfahrung und persönlicher Präferenz. Niemand soll Themen oder Klassenstufen unterrichten, die nicht zuverlässig abgedeckt werden können.'],
        ],
    ],
    'franzoesisch' => [
        'code' => 'FRA',
        'slug' => 'karriere-franzoesisch.php',
        'title' => 'Nachhilfelehrkraft Französisch',
        'claim' => 'Französisch sprechen, verstehen und mit Freude anwenden.',
        'intro' => 'Gesucht werden sprachbegeisterte Lehrkräfte, die Aussprache, Grammatik, Hörverstehen und Kommunikation lebendig miteinander verbinden.',
        'subjects' => ['Französisch', 'Konversation', 'Grammatik', 'Prüfungsvorbereitung'],
        'values' => ['Kommunikation auf Augenhöhe', 'Fehler als Lernschritt', 'Kulturelle Offenheit', 'Individuelle Sprachförderung'],
        'requirements' => ['Sehr gute Französischkenntnisse', 'Sichere Aussprache', 'Geduld beim Sprechtraining', 'Strukturierte Vorbereitung'],
        'profiles' => ['Lehramts- oder Romanistikstudierende', 'Muttersprachlerinnen und Muttersprachler mit Unterrichtserfahrung', 'Lehrkräfte', 'Sprachtrainerinnen und Sprachtrainer'],
        'images' => [
            ['src' => '/assets/img/learning/nachhilfe-team-02.webp', 'alt' => 'Kommunikative Lernsituation im Sprachunterricht', 'caption' => 'Sprache im Dialog erleben'],
            ['src' => '/assets/img/learning/nachhilfe-tafel-06.webp', 'alt' => 'Erklärung an einer Tafel', 'caption' => 'Grammatik anschaulich erklären'],
            ['src' => '/assets/img/learning/nachhilfe-erfahrung-09.webp', 'alt' => 'Erfolgserlebnis nach konzentrierter Lernarbeit', 'caption' => 'Fortschritte sichtbar machen'],
        ],
    ],
    'spanisch' => [
        'code' => 'SPAN',
        'slug' => 'karriere-spanisch.php',
        'title' => 'Nachhilfelehrkraft Spanisch',
        'claim' => 'Eine Weltsprache entdecken – verständlich, lebendig und persönlich.',
        'intro' => 'Gesucht werden Lehrkräfte, die Lernende zum Sprechen ermutigen und Grammatik mit alltagsnaher Kommunikation verbinden.',
        'subjects' => ['Spanisch', 'Konversation', 'Grammatik', 'Prüfungsvorbereitung'],
        'values' => ['Offenheit und kulturelle Neugier', 'Aktive Sprachverwendung', 'Motivation ohne Druck', 'Persönliche Lernbegleitung'],
        'requirements' => ['Sehr gute Spanischkenntnisse', 'Sichere Grammatik und Aussprache', 'Freude an interkulturellen Themen', 'Verbindliche Vorbereitung'],
        'profiles' => ['Lehramts- oder Romanistikstudierende', 'Muttersprachlerinnen und Muttersprachler mit didaktischer Erfahrung', 'Lehrkräfte', 'Geeignete Sprachtrainerinnen und Sprachtrainer'],
        'images' => [
            ['src' => '/assets/img/learning/nachhilfe-studium-04.webp', 'alt' => 'Sprachtraining mit digitalen Lernmitteln', 'caption' => 'Modern und abwechslungsreich lernen'],
            ['src' => '/assets/img/learning/nachhilfe-oberstufe-07.webp', 'alt' => 'Persönliche Prüfungsvorbereitung', 'caption' => 'Sicher in Prüfungen kommunizieren'],
            ['src' => '/assets/img/learning/nachhilfe-beratung-08.webp', 'alt' => 'Beratung und gemeinsame Lernplanung', 'caption' => 'Lernwege gemeinsam planen'],
        ],
    ],
    'soziale-faecher' => [
        'code' => 'SOZ',
        'slug' => 'karriere-soziale-faecher.php',
        'title' => 'Nachhilfelehrkraft Soziale Fächer',
        'claim' => 'Zusammenhänge erkennen. Quellen prüfen. Eigene Urteile begründen.',
        'intro' => 'Gesucht werden Lehrkräfte für Geschichte, Geographie, Gemeinschaftskunde, Sozialkunde, Ethik und verwandte Fächer.',
        'subjects' => ['Geschichte', 'Geographie', 'Gemeinschaftskunde/Sozialkunde', 'Ethik', 'Religion', 'Politische Bildung'],
        'values' => ['Respektvolle Diskussion', 'Quellenkritik und Sachlichkeit', 'Demokratisches Verantwortungsbewusstsein', 'Eigenständiges Denken'],
        'requirements' => ['Fundierte Kenntnisse in mindestens einem sozialen Fach', 'Fähigkeit, komplexe Zusammenhänge verständlich zu ordnen', 'Politische und weltanschauliche Ausgewogenheit', 'Verlässliche Unterrichtsvorbereitung'],
        'profiles' => ['Lehramtsstudierende und Lehrkräfte', 'Studierende der Geschichts-, Politik- oder Sozialwissenschaften', 'Geographinnen und Geographen', 'Philosophie-, Ethik- oder Religionsfachkräfte'],
        'images' => [
            ['src' => '/assets/img/learning/grundschule-gruppe.webp', 'alt' => 'Gemeinsames Gespräch über gesellschaftliche Themen', 'caption' => 'Diskutieren und begründen'],
            ['src' => '/assets/img/learning/nachhilfe-tafel-06.webp', 'alt' => 'Strukturierte Darstellung historischer Zusammenhänge', 'caption' => 'Komplexität verständlich ordnen'],
            ['src' => '/assets/img/learning/nachhilfe-beratung-08.webp', 'alt' => 'Gespräch auf Augenhöhe', 'caption' => 'Perspektiven respektvoll vergleichen'],
        ],
    ],
];
